### ISSUE TITLE
Add meta data to all dashboard admin pages

### ISSUE THREAD

**Issue by TituxMetal** [TituxMetal/remix-prod-reports#18]
# Acceptance Criteria

## Meta title on every dashboard pages

- [x] dashboard main index page
- [x] create workstation page
- [x] create user page
- [x] create role page
