### ISSUE TITLE
New layout for admin pages

### ISSUE THREAD

**Issue by TituxMetal** [TituxMetal/remix-prod-reports#20]
## Acceptance Criteria

- [x] admin pages must not be shown in dashboard menu
- [x] the main title must be `Dashboard -> Admin` or similar
- [x] make a better style for menu items

## Implementation Plan

- [x] move admin pages in `admin+` folder in dashboard.
- [x] show the separation in the url eg. `/dashboard/admin/users`
- [x] detect the pathname in url with `useLocation` hook

List of concerned pages:

- [x] users create/show
- [x] workstations create/show
- [x] roles create/show
- [x] reports create/show

- [x] report statuses create/show
- permissions create/show
