### ISSUE TITLE
Dashboard Workstation List Page

### ISSUE THREAD

**Issue by TituxMetal** [TituxMetal/remix-prod-reports#47]
## Description

As a team leader, I want to view a list of workstations and navigate to the reports associated with each workstation.

## Acceptance Criteria

- [x] The page should display a list of workstations.
- [x] Each workstation item in the list should be clickable.
- [x] Clicking on a workstation should navigate to the report list page for that workstation.

## Implementation Plan

- [x] Fetch data for all workstations from the database.
- [x] Design and implement the UI layout for displaying the list of workstations.
- [x] Implement logic to handle clicking on a workstation item and navigate to the report list page for that workstation.
